### PR TITLE
Rebuild for proj 8.2.0 and gdal 3.4

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I was reviewing conda-forge migrations and found this repo to be needing some help for migrations.  So will see if this helps clear a logjam

### CODE REVIEW

**Comment by akrherz** [comment]
Ah OK, so

>  - package r-base-4.1.0-h9e01966_0 requires icu >=68.1,<69.0a0, but none of the providers can be installed

it is jammed due to icu69 migration here conda-forge/r-base-feedstock#193

**Comment by akrherz** [comment]
Lets try again, maybe helped by conda-forge/gdal-feedstock#585

@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Great, this PR is now green :)

**Comment by akrherz** [comment]
I think that taking this will allow #17 to then work, but am not fully certain.

**Comment by cbrueffer** [comment]
Thanks!

**Pull request merged**
